workflows:
     react-native-android:
        name: React Native Android
        max_build_duration: 60
        instance_type: linux_x2
        environment:
            node: 16.11.1
        cache:
           cache_paths:
               - $CM_BUILD_DIR/node_modules
        scripts:
            - sleep 15
            - name: Install npm dependencies
              script: yarn install
     
